SistemaGestionEventos/SistemaGestionEventos/Controllers/EventoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaGestionEventos.Models;
using SistemaGestionEventos.Servicios;

namespace SistemaGestionEventos.Controllers
{
    public class EventoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepositorioEvento repositorioEvento;
        private readonly IRepositorioPatrocinador repositorioPatrocinador;
        private readonly IRepositorioTipoEvento repositorioTipoEvento;
        private readonly IRepositorioUbicacion repositorioUbicacion;
        private readonly IMapper mapper;

        public EventoController
            (IRepositorioPatrocinador repositorioPatrocinador,
            IRepositorioTipoEvento repositorioTipoEvento,
            IRepositorioUbicacion repositorioUbicacion,
            IRepositorioEvento repositorioEvento,
            ILogger<HomeController> logger,
            IMapper mapper)
        {
            this.repositorioPatrocinador = repositorioPatrocinador;
            this.repositorioTipoEvento = repositorioTipoEvento;
            this.repositorioUbicacion = repositorioUbicacion;
            this.repositorioEvento = repositorioEvento;
            _logger = logger;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var evento = await repositorioEvento.Obtener();
            return View(evento);
        }

        //Crear un nuevo evento
        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var modelo = new EventoCrearViewModel();

            modelo.TipoEventoList = await ObtenerTipoEventos();
            modelo.UbicacionList = await ObtenerUbicaciones();
            modelo.PatrocinadorList = await ObtenerPatrocinadores();

            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(EventoCrearViewModel modelo)
        {
            if (!ModelState.IsValid)
            {
                modelo.TipoEventoList = await ObtenerTipoEventos();
                modelo.UbicacionList = await ObtenerUbicaciones();
                modelo.PatrocinadorList = await ObtenerPatrocinadores();
                return View(modelo);
            }

            var tipoEvento = await repositorioTipoEvento.ObtenerPorId(modelo.TipoEventoId);
            if (tipoEvento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var ubicacion = await repositorioUbicacion.ObtenerId(modelo.UbicacionId);
            if (ubicacion is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var patrocinador = await repositorioPatrocinador.ObtenerId(modelo.PatrocinadorId);
            if (patrocinador is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorioEvento.Crear(modelo);

            return RedirectToAction("Index");

        }

        //Eliminar un evento
        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            var evento = await repositorioEvento.ObtenerId(id);

            if (evento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(evento);

        }

        [HttpPost]
        public async Task<IActionResult> EliminarConfirm(int id)
        {
            var evento = await repositorioEvento.ObtenerId(id);

            if (evento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorioEvento.Eliminar(id);

            return RedirectToAction("Index");

        }

        //Editar un evento
        public async Task<IActionResult> Editar(int id)
        {
            var evento = await repositorioEvento.ObtenerId(id);

            if (evento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var modelo = mapper.Map<EventoCrearViewModel>(evento);
            //var modelo = new EventoCrearViewModel
            //{
            //    Id = evento.Id,
            //    Nombre = evento.Nombre,
            //    UbicacionId = evento.UbicacionId,
            //    TipoEventoId = evento.TipoEventoId,
            //    FechaInicio = evento.FechaInicio,
            //    FechaFinal = evento.FechaFinal,
            //    PrecioDeEntrada = evento.PrecioDeEntrada,
            //    PatrocinadorId = evento.PatrocinadorId,
            //    Descripcion = evento.Descripcion,
            //};

            modelo.TipoEventoList = await ObtenerTipoEventos();
            modelo.UbicacionList = await ObtenerUbicaciones();
            modelo.PatrocinadorList = await ObtenerPatrocinadores();


            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(EventoCrearViewModel modelo)
        {
            var evento = await repositorioEvento.ObtenerId(modelo.Id);

            if (!ModelState.IsValid)
            {
                modelo.TipoEventoList = await ObtenerTipoEventos();
                modelo.UbicacionList = await ObtenerUbicaciones();
                modelo.PatrocinadorList = await ObtenerPatrocinadores();
                return View(modelo);
            }

            if (evento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var tipoEvento = await repositorioTipoEvento.ObtenerPorId(modelo.TipoEventoId);
            if (tipoEvento is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var ubicacion = await repositorioUbicacion.ObtenerId(modelo.UbicacionId);
            if (ubicacion is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var patrocinador = await repositorioPatrocinador.ObtenerId(modelo.PatrocinadorId);
            if (patrocinador is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorioEvento.Editar(modelo);

            return RedirectToAction("Index");
        }



        //Obtener datos de tipoEvento Ubicaciones y patrocinadores
        private async Task<IEnumerable<SelectListItem>> ObtenerTipoEventos()
        {
            var tiposEvento = await repositorioTipoEvento.Obtener();
            return tiposEvento.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }

        private async Task<IEnumerable<SelectListItem>> ObtenerUbicaciones()
        {
            var ubicaciones = await repositorioUbicacion.Obtener();
            return ubicaciones.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }

        private async Task<IEnumerable<SelectListItem>> ObtenerPatrocinadores()
        {
            var patrocinadores = await repositorioPatrocinador.Obtener();
            return patrocinadores.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }
    }
}

SistemaGestionEventos/SistemaGestionEventos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaGestionEventos.Models;
using System.Diagnostics;
using System.Diagnostics.Contracts;

namespace SistemaGestionEventos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult CentroDeEventos() 
        {
            return View();
        }

        public IActionResult MisEventos() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaGestionEventos/SistemaGestionEventos/Controllers/TipoEventoController.cs
using AutoMapper;
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using SistemaGestionEventos.Models;
using SistemaGestionEventos.Servicios;
using System.Reflection;

namespace SistemaGestionEventos.Controllers
{
    public class TipoEventoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepositorioTipoEvento repositorioTipoEvento;
        private readonly IMapper mapper;


        public TipoEventoController(
            IRepositorioTipoEvento repositorioTipoEvento,
            IMapper mapper
,
            ILogger<HomeController> logger)
        {
            this.repositorioTipoEvento = repositorioTipoEvento;
            this.mapper = mapper;
            _logger = logger;
        }

        //Vista principal
        public async Task<IActionResult> Index() 
        {
            var tipoEvento = await repositorioTipoEvento.Obtener();
            return View(tipoEvento);
        }

        //Crear Nuevo Tipo Evento
        [HttpGet]
        public IActionResult Crear() 
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoEvento tipoEvento) 
        {
            if (!ModelState.IsValid) 
            {
                return View(tipoEvento);
            }

            var tipoEventoExiste = await repositorioTipoEvento.Existe(tipoEvento.Nombre);

            if (tipoEventoExiste) 
            {
                ModelState.AddModelError(nameof(tipoEvento.Nombre), $"El nombre {tipoEvento.Nombre} ya existe");
                return View(tipoEvento);
            }

            _logger.LogInformation("Modelo recibido: {Modelo}", tipoEvento.Nombre);


            await repositorioTipoEvento.Crear(tipoEvento);
            return RedirectToAction("Index");   
        }

        //Eliminar Tipo Evento
        [HttpGet]
        public async Task<IActionResult> Eliminar(int id) 
        {
            var tipoCuenta = await repositorioTipoEvento.ObtenerPorId(id);

            if (tipoCuenta is null) 
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(tipoCuenta);
        }

        [HttpPost]
        public async Task<IActionResult> EliminarConfirm(int id) 
        {
            var tipoEvento = await repositorioTipoEvento.ObtenerPorId(id);

            if (tipoEvento is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTipoEvento.Eliminar(id);
            return RedirectToAction("Index");
        }

        //Editar un tipo de evento
        [HttpGet]
        public async Task<IActionResult> Editar(int id) 
        {
            var tipoEvento = await repositorioTipoEvento.ObtenerPorId(id);

            //var modelo = mapper.Map<TipoEventoCrearViewModel>(tipoEvento);
            var editarTipoEvento = new EditarTipoEventoViewModel
            {
                Id = tipoEvento.Id,
                Nombre = tipoEvento.Nombre,
                Descripcion = tipoEvento.Descripcion,
            };

            if (tipoEvento is null)
            {
                return View("NotFound", "Home");
            }

            return View(editarTipoEvento);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(EditarTipoEventoViewModel editarTipoEvento) 
        {
            if (!ModelState.IsValid)
            {
                return View(editarTipoEvento);
            }

            await repositorioTipoEvento.Editar(editarTipoEvento);

            return RedirectToAction("Index");
        }

    }
}

SistemaGestionEventos/SistemaGestionEventos/Controllers/UbicacionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SistemaGestionEventos.Models;
using SistemaGestionEventos.Servicios;

namespace SistemaGestionEventos.Controllers
{
    public class UbicacionController : Controller
    {
        private readonly IRepositorioUbicacion repositorioUbicacion;
        private readonly IMapper mapper;
        public UbicacionController(IRepositorioUbicacion repositorioUbicacion, IMapper mapper)
        {
            this.repositorioUbicacion = repositorioUbicacion;
            this.mapper = mapper;
        }

        //Vista principal de ubicaciones
        public async Task<IActionResult> Index()
        {
            var ubicacion = await repositorioUbicacion.Obtener();
            return View(ubicacion);
        }

        //Funcion de agregar nueva ubicacion
        [HttpGet]
        public IActionResult Crear() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Ubicacion ubicacion) 
        {
            if (!ModelState.IsValid) 
            {
                return View(ubicacion);
            }

            var ubicacionExiste = await repositorioUbicacion.Existe(ubicacion.Nombre);

            if (ubicacionExiste) 
            {
                ModelState.AddModelError(nameof(ubicacion.Nombre), $"El nombre {ubicacion.Nombre} ya existe");
                return View(ubicacion);
            }

            await repositorioUbicacion.Crear(ubicacion);
            return RedirectToAction("Index");
        }

        //Funcion de eliminar una ubicacion.
        [HttpGet]
        public async Task<IActionResult> Eliminar(int id) 
        {
            var ubicacion = await repositorioUbicacion.ObtenerId(id);

            if (ubicacion is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(ubicacion);
        }

        [HttpPost]

        public async Task<IActionResult> EliminarConfirm (int id) 
        {
            var ubicacion = await repositorioUbicacion.ObtenerId(id);

            if (ubicacion is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioUbicacion.Eliminar(id);
            return RedirectToAction("Index");
        }

        //Funcion editar una ubicacion
        [HttpGet]
        public async Task<IActionResult> Editar(int id) 
        {
            var ubicacion = await repositorioUbicacion.ObtenerId(id);

            var editarUbicacion = new UbicacionEditarViewModel
            {
                Id = ubicacion.Id,
                Nombre = ubicacion.Nombre,
                Direccion = ubicacion.Direccion,
                DireccionUrl = ubicacion.DireccionUrl,
                CapacidadPersonas = ubicacion.CapacidadPersonas,
                Servicios = ubicacion.Servicios,
                Descripcion = ubicacion.Descripcion,
            };

            if (ubicacion is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(editarUbicacion);
        }

        [HttpPost]

        public async Task<IActionResult> Editar(UbicacionEditarViewModel editarUbicacion) 
        {
            if (!ModelState.IsValid)
            {
                return View(editarUbicacion);
            }

            if (editarUbicacion is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorioUbicacion.Editar(editarUbicacion);
            return RedirectToAction("Index");
        }
    }
}

SistemaGestionEventos/SistemaGestionEventos/Views/Home/CentroDeEventos.cshtml
@{
    ViewData["Title"] = "Event Central - Centro De Eventos";
}

@*Titulo y Presentacion*@
<div class="encabezado_box miFuente">
    <div class="row">
        <div class="col mt-5 mb-5" style="text-align:center;">
            <img src="~/media/logo-EventCentral.png" alt="logo del sistema" class="logoEventCentral mb-5"/>
            <h4 class="tamaño_Titulos"><i class="bi bi-house-gear-fill"></i></h4>
            <h3 class="tamaño_Titulos">Esto es el centro de eventos</h3>
            <p class="tamaño_Texto">
                Aquí podrás tener fácil acceso a las funciones del sistema como crear un nuevo evento,
                administrar los datos de los patrocinadores, usuarios, ubicaciones.
                Además de las funciones de edición a tus eventos como editar, eliminar y actualizar
            </p>
        </div>
    </div>
</div>

@*Edicion de eventos*@

<div class="miFuente mt-5 mb-5">
    <div class="row mb-5 mt-5">
        <div class="col img_box_1">
            <div class="mt-4">
                <h3 class="tamaño_SubTitulos">Eventos <i class="bi bi-calendar2-event-fill"></i></h3>
                <p class="tamaño_Texto">
                    Crea un nuevo evento desde 0 o también puedes editar eventos ya existentes
                    en la lista de control.
                </p>
                <div style="text-align:center;">
                    <a asp-controller="Evento" asp-action="Index" class="btn botones_estilo_2 miFuente">Eventos</a>
                </div>
            </div>
        </div>

        <div class="col centrarHorizontal">
            <img src="~/media/Eventos.png" alt="Persona en EventCentral" class="img_box_Circular_1"></img>
        </div>

    </div>
</div>


@*Edicion de Tipo de eventos*@

<div class="miFuente mt-5 mb-5">
    <div class="row mb-5 mt-5">
        <div class="col">
            <div>
                <img src="~/media/eventoPublico.jpg" class="img_box_Circular_1"></img>
                <img src="~/media/EventoPrivado.jpg" class="img_box_Circular_1" 
                style="margin-top:-370px; margin-left:250px;"></img>
            </div>
        </div>

        <div class="col img_box_2">
            <div class="mt-4">
                <h3 class="tamaño_SubTitulos">Tipos de eventos <i class="bi bi-archive-fill"></i></h3>
                <p class="tamaño_Texto">
                    Evento Central ya cuenta con una seria de categorías para los diferentes tipos de eventos,
                    pero también puedes crear tus propios tipos de eventos personalizados.
                </p>
                <div style="text-align:center;">
                    <a asp-controller="TipoEvento" asp-action="Index" class="btn botones_estilo_2 miFuente">
                        Tipos de eventos</a>
                </div>
            </div>
        </div>
    </div>
</div>


@*Ubicaciones*@

<div class="miFuente mt-5 mb-5">
        <div class="row mb-5 mt-5">
            <div class="col img_box_3">
                <div class="mt-4">
                    <h3 class="tamaño_SubTitulos">Ubicaciones <i class="bi bi-globe-americas"></i></h3>
                    <p class="tamaño_Texto">
                        Puedes almacenar los datos referentes a ubicaciones especificas como teatros,
                        galerias de arte, centros publicos, etc.
                    </p>
                    <div style="text-align:center;">
                        <a asp-controller="Ubicacion" asp-action="Index" class="btn botones_estilo_2 miFuente">Ubicaciones</a>
                    </div>
                </div>
            </div>

            <div class="col centrarHorizontal">
                <img src="~/media/mapa.png" class="img_box_Circular_1"></img>
            </div>
        </div>
</div>


@*Patrocinadores*@

<div class="miFuente mt-5 mb-5">
    <div class="row mb-5 mt-5">
        <div class="col centrarHorizontal">
            <img src="~/media//patrocinadores.jpg" class="img_box_Circular_1"></img>
        </div>

        <div class="col img_box_4">
            <div class="mt-4">
                <h3 class="tamaño_SubTitulos">Patrocinadores <i class="bi bi-wallet-fill"></i></h3>
                <p class="tamaño_Texto">
                    Si tu evento cuenta con patrocinadores puedes almacenar sus datos como el nombre de la empresa,
                    persona u organizacion que te patrocinan y formas de contactar con ellos.
                </p>
                <div style="text-align:center;">
                    <a asp-controller="Patrocinador" asp-action="Index" class="btn botones_estilo_2 miFuente">
                        Patrocinadores
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


@*Usuarios*@

SistemaGestionEventos/SistemaGestionEventos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Event Center - Pagina Principal";
}

@*Titulo y logo*@
<div class="encabezado_box">
    <div class="row mb-5">
        <div class="col mt-5 mb-5 centrarHorizontal">
            <img src="~/media/logo-EventCentral.png" class="logoEventCentral" />
        </div>
        <div class="col miFuente centrarVertical">
            <div>
                <h1 class="tamaño_Titulos">Event Central</h1>
                <h2>"Organiza tus eventos de forma fácil y eficiente con nuestro sistema de gestión."</h2>
            </div>
        </div>
    </div>
</div>


@*Imagenes y textos bloque 1 (2 filas)*@
<div class="miFuente row mb-5 sombreadoBackground">
    <div class="col">
        <img src="~/media/ejemploEvento-2.jpg" class="img_box_1" alt="Evento publico" />
    </div>

    <div class="col centrarVertical">
        <div>
            <h2 class="tamaño_SubTitulos">Esto es Event Central</h2>
            <h4 class="tamaño_Texto">Un sistema de gestión de eventos de todo tipo, ya sean públicos o privados</h4>
        </div>
    </div>
</div>

<div class="miFuente row">
    <div class="col centrarVertical">
        <div>
            <h2 class="tamaño_SubTitulos">Puedes organizar todo tipo de eventos</h2>
            <h4 class="tamaño_Texto">Espectáculos, Conferencias, Ferias, Exhibiciones, Eventos de caridad o recaudación de fondos </h4>
        </div>
    </div>

    <div class="col d-flex justify-content-end">
        <img src="~/media/ejemploEvento-3.jpg" class="img_box_2" alt="Evento publico"/>
    </div>
</div>

@*Botones para funciones*@
<div class="encabezado_box mt-5 mb-5 miFuente centrarHorizontal">
    <div class="row">
        <div class="col mt-5 mb-5">
            <h4 class="tamaño_Titulos"><i class="bi bi-house-fill"></i></h4>
            <h2 class="tamaño_SubTitulos">Comienza a utilizar nuestro servicio.</h2>
        </div>
        <div class="row mb-5">
            <div class="col">
                <h3>Ve al centro de eventos</h3>
                <a asp-action="CentroDeEventos" class="btn botones_estilo_1 mt-3">Centro De Eventos <i class="bi bi-house-gear-fill"></i> </a>
            </div>
            <div class="col">
                <h3>Dale un vistazo a tus eventos</h3>
                <a asp-action="MisEventos" class="btn botones_estilo_1 mt-3">Mis Eventos <i class="bi bi-card-list"></i></a>
            </div>
            
        </div>
    </div>
    
</div>

@*Imagenes y textos bloque 2 (2 filas)*@
<div class="miFuente row mb-5 sombreadoBackground">
    <div class="col  ">
        <img src="~/media/ejemploEvento-4.jpg" class="img_box_3" alt="Evento publico" />
    </div>

    <div class="col  centrarVertical">
        <div>
            <h2 class="tamaño_SubTitulos">Fácil y Completo</h2>
            <h4 class="tamaño_Texto">
                Un sistema de gestión diseñado para ser simple,
                pero al mismo tiempo poder manipular la información de forma eficiente
            </h4>
        </div>
    </div>
</div>

<div class="miFuente row" >
    <div class="col mt-5 centrarVertical">
        <div>
            <h2 class="tamaño_SubTitulos">Para uso personal y profesional</h2>
            <h4 class="tamaño_Texto">
                Puedes usar Event Central como una agenda de eventos personales
                o como un gestor completo de eventos públicos y privados
            </h4>
        </div>
    </div>

    <div class="col mt-5 d-flex justify-content-end">
        <img src="~/media/ejemploEvento-1.jpg" class="img_box_4" alt="Evento publico"/>
    </div>
</div>

SistemaGestionEventos/SistemaGestionEventos/Views/Home/NotFound.cshtml
@{
    ViewData["Title"] = "No encontrado";
}

<div class="row encabezado_box">
    <div class="col">
        <h1 class="tamaño_Titulos">El valor solicitado no existe</h1>
    </div>
</div>